// <auto-generated />
namespace mine.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_table_Topic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_table_Topic));
        
        string IMigrationMetadata.Id
        {
            get { return "201607050607049_add_table_Topic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
