// <auto-generated />
namespace mine.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 添加customerLanguage表等 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(添加customerLanguage表等));
        
        string IMigrationMetadata.Id
        {
            get { return "201606280356336_添加customer、Language表等"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
